import type { Invoice } from '../../types/erp';
import { useApp } from '../../context/AppContext';

interface Props {
  invoice: Invoice | null;
  onClose: () => void;
}

export function InvoiceModal({ invoice, onClose }: Props) {
  const { currentUser } = useApp();
  if (!invoice) return null;

  const handlePrint = () => {
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <!DOCTYPE html><html><head><title>Invoice ${invoice.id}</title>
      <style>
        body{font-family:sans-serif;padding:20px;color:#1e1b4b;max-width:600px;margin:auto}
        h1{font-size:22px;margin-bottom:4px}h2{font-size:14px;color:#555;font-weight:normal;margin-bottom:20px}
        .meta{display:flex;justify-content:space-between;margin-bottom:24px;padding-bottom:12px;border-bottom:2px solid #e5e7eb}
        table{width:100%;border-collapse:collapse;margin-bottom:16px}
        th{background:#f3f4f6;text-align:left;padding:8px 10px;font-size:12px;text-transform:uppercase;letter-spacing:.05em}
        td{padding:8px 10px;border-bottom:1px solid #e5e7eb;font-size:13px}
        .totals{text-align:right}.total-row{font-weight:bold;font-size:16px;color:#7c3aed}
        .footer{text-align:center;margin-top:24px;color:#9ca3af;font-size:11px}
      </style></head><body>
      <h1>⚡ ${currentUser?.businessName ?? 'NexaERP Business'}</h1>
      <h2>${currentUser?.phone ?? ''} · ${currentUser?.email ?? ''}</h2>
      <div class="meta">
        <div><strong>Invoice:</strong> ${invoice.id}<br/><strong>Date:</strong> ${invoice.date}<br/><strong>Customer:</strong> ${invoice.customerName}<br/><strong>Phone:</strong> ${invoice.customerPhone}</div>
        <div style="text-align:right"><strong>Status:</strong> PAID<br/>${invoice.gstEnabled ? `<strong>GST:</strong> Inclusive` : 'Non-GST Invoice'}</div>
      </div>
      <table>
        <thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Price</th>${invoice.gstEnabled ? '<th>GST</th>' : ''}<th>Total</th></tr></thead>
        <tbody>
        ${invoice.items.map((it, i) => `<tr><td>${i + 1}</td><td>${it.name}</td><td>${it.qty}</td><td>₹${it.price}</td>${invoice.gstEnabled ? `<td>${it.gst}%</td>` : ''}<td>₹${it.total.toFixed(2)}</td></tr>`).join('')}
        </tbody>
      </table>
      <div class="totals">
        <div>Subtotal: ₹${invoice.subtotal.toLocaleString()}</div>
        ${invoice.gstEnabled ? `<div>GST: +₹${invoice.gstTotal.toFixed(2)}</div>` : ''}
        ${invoice.discount > 0 ? `<div>Discount: -₹${invoice.discount.toFixed(2)}</div>` : ''}
        <div class="total-row">Grand Total: ₹${invoice.grandTotal.toFixed(2)}</div>
      </div>
      <div class="footer">Thank you for your business! · Generated by NexaERP</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const handleWhatsApp = () => {
    if (!invoice.customerPhone) return;
    const msg = encodeURIComponent(
      `*${currentUser?.businessName ?? 'NexaERP'}*\nInvoice: ${invoice.id}\nDate: ${invoice.date}\nItems: ${invoice.items.map(i => `${i.name} x${i.qty}`).join(', ')}\nTotal: ₹${invoice.grandTotal.toFixed(2)}\n\nThank you!`
    );
    window.open(`https://wa.me/91${invoice.customerPhone}?text=${msg}`, '_blank');
  };

  const handleDownload = () => {
    const csv = [
      'Item,Qty,Price,GST%,Total',
      ...invoice.items.map(i => `${i.name},${i.qty},${i.price},${i.gst},${i.total.toFixed(2)}`),
      `,,,,`,
      `Subtotal,,,, ₹${invoice.subtotal}`,
      invoice.gstEnabled ? `GST Total,,,, ₹${invoice.gstTotal.toFixed(2)}` : '',
      invoice.discount > 0 ? `Discount,,,, -₹${invoice.discount.toFixed(2)}` : '',
      `Grand Total,,,, ₹${invoice.grandTotal.toFixed(2)}`,
    ].filter(Boolean).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `Invoice_${invoice.id}.csv`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative glass rounded-3xl w-full max-w-lg shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-white/10">
          <div>
            <h3 className="font-extrabold text-indigo-900 dark:text-white">🧾 Invoice Preview</h3>
            <p className="text-xs text-indigo-600 dark:text-white/50 mt-0.5">{invoice.id} · {invoice.date}</p>
          </div>
          <button onClick={onClose} className="btn-glass w-8 h-8 rounded-xl flex items-center justify-center text-indigo-900 dark:text-white">✕</button>
        </div>

        <div className="p-5 space-y-4">
          {/* Business & Customer */}
          <div className="flex justify-between glass rounded-2xl p-4">
            <div>
              <div className="text-xs text-indigo-600 dark:text-white/50 mb-0.5">From</div>
              <div className="font-bold text-indigo-900 dark:text-white text-sm">{currentUser?.businessName ?? 'NexaERP Business'}</div>
              <div className="text-xs text-indigo-600 dark:text-white/50">{currentUser?.phone}</div>
            </div>
            <div className="text-right">
              <div className="text-xs text-indigo-600 dark:text-white/50 mb-0.5">To</div>
              <div className="font-bold text-indigo-900 dark:text-white text-sm">{invoice.customerName}</div>
              <div className="text-xs text-indigo-600 dark:text-white/50">{invoice.customerPhone || '—'}</div>
            </div>
          </div>

          {/* Items Table */}
          <div className="glass rounded-2xl overflow-hidden">
            <table className="w-full erp-table">
              <thead><tr><th>Item</th><th>Qty</th><th>Rate</th>{invoice.gstEnabled && <th>GST</th>}<th className="text-right">Total</th></tr></thead>
              <tbody>
                {invoice.items.map((item, i) => (
                  <tr key={i}>
                    <td className="font-medium text-xs">{item.name}</td>
                    <td className="text-xs">{item.qty}</td>
                    <td className="text-xs">₹{item.price}</td>
                    {invoice.gstEnabled && <td className="text-xs text-amber-600 dark:text-amber-400">{item.gst}%</td>}
                    <td className="text-right font-bold text-sm text-violet-600 dark:text-violet-400">₹{item.total.toFixed(0)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="glass rounded-2xl p-4 space-y-2">
            <div className="flex justify-between text-sm text-indigo-900 dark:text-white/80"><span>Subtotal</span><span>₹{invoice.subtotal.toLocaleString()}</span></div>
            {invoice.gstEnabled && <div className="flex justify-between text-sm text-amber-600 dark:text-amber-400"><span>GST</span><span>+₹{invoice.gstTotal.toFixed(0)}</span></div>}
            {invoice.discount > 0 && <div className="flex justify-between text-sm text-emerald-600 dark:text-emerald-400"><span>Discount</span><span>-₹{invoice.discount.toFixed(0)}</span></div>}
            <div className="border-t border-white/20 pt-2 flex justify-between font-extrabold text-lg text-indigo-900 dark:text-white">
              <span>Grand Total</span>
              <span className="text-violet-600 dark:text-violet-400">₹{invoice.grandTotal.toFixed(0)}</span>
            </div>
            <div className="flex items-center gap-2 pt-1">
              <div className="w-2 h-2 rounded-full bg-emerald-400 pulse-dot" />
              <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">PAID</span>
              <span className="text-xs text-indigo-600 dark:text-white/40 ml-auto">{invoice.gstEnabled ? 'GST Invoice' : 'Non-GST Invoice'}</span>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-3 gap-2">
            <button onClick={handlePrint} className="btn-primary py-2.5 rounded-xl text-xs font-bold flex flex-col items-center gap-1">
              🖨️ Print
            </button>
            <button onClick={handleWhatsApp} disabled={!invoice.customerPhone}
              className="bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30 py-2.5 rounded-xl text-xs font-bold hover:bg-emerald-500/30 transition-colors disabled:opacity-40 flex flex-col items-center gap-1">
              💬 WhatsApp
            </button>
            <button onClick={handleDownload} className="btn-glass py-2.5 rounded-xl text-xs font-bold text-indigo-900 dark:text-white flex flex-col items-center gap-1">
              📥 Download
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
